name: 'GatorGradle'
description: 'Execute GatorGradle'
author: 'Saejin Mahlau-Heinert'
runs:
  using: 'composite'
  steps:
    - run: |
        echo "::group::Install Pipenv"
        pip install pipenv
        echo "::endgroup::"
        gradle grade
      shell: bash
branding:
  icon: 'user-check'
  color: 'green'
